"""Usage curve template model."""
from decimal import Decimal
from sqlalchemy import Integer, String, Numeric, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base
from app.models.base import TimestampMixin, SoftDeleteMixin, RegionMixin

class UsageCurveTemplate(TimestampMixin, SoftDeleteMixin, RegionMixin, Base):
    __tablename__ = "elec_usage_curve_template"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    template_name: Mapped[str | None] = mapped_column(String(100))
    description: Mapped[str | None] = mapped_column(Text)
    template_type: Mapped[int | None] = mapped_column(Integer)
    industry: Mapped[str | None] = mapped_column(String(50))
    image_url: Mapped[str | None] = mapped_column(String(200))
    # 24h normal ratios
    hour_00_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_01_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_02_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_03_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_04_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_05_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_06_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_07_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_08_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_09_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_10_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_11_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_12_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_13_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_14_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_15_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_16_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_17_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_18_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_19_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_20_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_21_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_22_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_23_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    # 24h peak month ratios
    hour_00_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_01_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_02_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_03_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_04_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_05_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_06_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_07_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_08_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_09_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_10_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_11_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_12_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_13_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_14_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_15_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_16_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_17_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_18_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_19_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_20_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_21_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_22_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    hour_23_peak_ratio: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    status: Mapped[int | None] = mapped_column(Integer, default=1)
    is_default: Mapped[int | None] = mapped_column(Integer, default=0)
    sort: Mapped[int | None] = mapped_column(Integer)
