[alembic]
script_location = app/alembic
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic
[handlers]
keys = console
[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
[logger_sqlalchemy]
level = WARN
qualname = sqlalchemy.engine
handlers =
[logger_alembic]
level = INFO
qualname = alembic
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
